name: deployment
# 触发条件
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch: # 允许手动运行，便于调试
    branches:
      - main
# 任务
jobs:
  deploy:
    # 运行的环境
    runs-on: ubuntu-latest
    # 限制主仓库运行
    if: github.repository == 'BUAA-Software-Engineering-2023/Hospital-Frontend'
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: 打包镜像, 上传 Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t hospital .
          docker tag hospital ${{ secrets.DOCKER_REPOSITORY }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}

      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "login" > log.txt
            sudo docker rm hospital -f
            sudo docker rmi ${{ secrets.DOCKER_REPOSITORY }}
            sudo docker pull ${{ secrets.DOCKER_REPOSITORY }}
            sudo docker run -d -p 80:80 --name hospital ${{ secrets.DOCKER_REPOSITORY }}